WIDTH = 40;
LENGTH = 150;
BASE_HEIGHT = 20;
WALL_THICKNESS = 5;

DISTANCE_OF_HOLE_FROM_EDGE = 4;
KEY_SIZE = 4;

ACRYLIC_THICKNESS = 6.5;
SLOT_HEIGHT = 30;

HEIGHT_OF_HALF_WALL = 12;

RASPI_WIDTH = 23;
RASPI_LENGTH = 58;
HOLE_RADIUS = 1.2;

STRIP_HEIGHT = 2;